const chapters = [
 { msg: "An Overview of C++", href: "/w01/A#A" },
 { msg: "The C++ Programming Language", href: "/w01/A#B" },
 { msg: "Hello World", href: "/w01/A#C" },
 { msg: "Source Code", href: "/w01/A#D" },
 { msg: "Program Mechanics", href: "/w01/A#E" },
 { msg: "The Build Process", href: "/w01/A#F" },
 { msg: "Early Computing", href: "/w01/B#A" },
 { msg: "Machine Language", href: "/w01/B#B" },
 { msg: "High-Level Languages", href: "/w01/B#C" },
 { msg: "The C Language", href: "/w01/B#D" },
 { msg: "Object-Oriented Programming", href: "/w01/B#E" },
 { msg: "The C++ Language", href: "/w01/B#F" },
 { msg: "C++ Syntax", href: "/w01/C#A" },
 { msg: "The f2c Program", href: "/w01/C#B" },
 { msg: "The Standard C++ Library", href: "/w01/C#C" },
 { msg: "The main Function", href: "/w01/C#D" },
 { msg: "The convert Function", href: "/w01/C#E" },
 { msg: "Variables", href: "/w01/D#A" },
 { msg: "Definitions & Types", href: "/w01/D#B" },
 { msg: "Identifiers & Constants", href: "/w01/D#C" },
 { msg: "Initialization", href: "/w01/D#D" },
 { msg: "Assignment", href: "/w01/D#E" },
 { msg: "Console Output", href: "/w01/D#F" },
 { msg: "Console Input", href: "/w01/D#G" },
 { msg: "Integers", href: "/w01/E#A" },
 { msg: "Signed & Unsigned", href: "/w01/E#B" },
 { msg: "Integer Literals", href: "/w01/E#C" },
 { msg: "Floating-point Numbers", href: "/w01/E#D" },
 { msg: "Floating-point Output", href: "/w01/E#E" },
 { msg: "Expressions", href: "/w01/E#F" },
 { msg: "Expression Evaluation", href: "/w01/E#G" },
 { msg: "Integer Division & Remainders", href: "/w02/A#A" },
 { msg: "Assignment Operators", href: "/w02/A#B" },
 { msg: "Increment and Decrement", href: "/w02/A#C" },
 { msg: "Mixed-type Expressions", href: "/w02/A#D" },
 { msg: "Type Casts", href: "/w02/A#E" },
 { msg: "Functions", href: "/w02/A#F" },
 { msg: "The <cmath > Header", href: "/w02/A#G" },
 { msg: "Writing Functions", href: "/w02/B#A" },
 { msg: "Function Syntax", href: "/w02/B#B" },
 { msg: "The Function Body", href: "/w02/B#C" },
 { msg: "Functional Decomposition", href: "/w02/B#D" },
 { msg: "Declaring & Defining", href: "/w02/B#E" },
 { msg: "Making Decisions", href: "/w02/C#A" },
 { msg: "Blocks, Style & Indentation", href: "/w02/C#B" },
 { msg: "The bool Data Type", href: "/w02/C#C" },
 { msg: "The Relational Operatorrs", href: "/w02/C#D" },
 { msg: "The Logical Operators", href: "/w02/C#E" },
 { msg: "Multi-way Branching", href: "/w02/C#F" },
 { msg: "Nested if Statements", href: "/w02/C#G" },
 { msg: "Creating String Object", href: "/w02/D#A" },
 { msg: "String Input and Output", href: "/w02/D#B" },
 { msg: "Concatenation & Comparison", href: "/w02/D#C" },
 { msg: "Mutability & Value Assignment", href: "/w02/D#D" },
 { msg: "Member Functions", href: "/w02/D#E" },
 { msg: "String Members", href: "/w02/E#A" },
 { msg: "Characters", href: "/w02/E#B" },
 { msg: "Selecting Characters", href: "/w02/E#C" },
 { msg: "Substrings", href: "/w02/E#D" },
 { msg: "Searching a String", href: "/w02/E#E" },
 { msg: "References", href: "/w03/A#A" },
 { msg: "Conversions & Const-ref", href: "/w03/A#B" },
 { msg: "Reference Parameters", href: "/w03/A#C" },
 { msg: "String Value Parameters", href: "/w03/A#D" },
 { msg: "String Reference Parameters", href: "/w03/A#E" },
 { msg: "Introducing Loops", href: "/w03/B#A" },
 { msg: "Guarded & Unguarded Loops", href: "/w03/B#B" },
 { msg: "Classifying Loops", href: "/w03/B#C" },
 { msg: "Indefinite Loop Categories", href: "/w03/B#D" },
 { msg: "Range-based Loops", href: "/w03/B#E" },
 { msg: "Definite Loops with for", href: "/w03/C#A" },
 { msg: "Sequences & Symmetric Bounds", href: "/w03/C#B" },
 { msg: "Processing Strings", href: "/w03/C#C" },
 { msg: "Some Bad Habits", href: "/w03/C#D" },
 { msg: "Hands On: Counting Vowels", href: "/w03/C#E" },
 { msg: "Hands On: Counting Substrings", href: "/w03/C#F" },
 { msg: "More Efficient Substrings", href: "/w03/C#G" },
 { msg: "Substrings Redux", href: "/w03/C#H" },
 { msg: "Goal, Bounds & Plan", href: "/w03/D#A" },
 { msg: "Implement the Plan", href: "/w03/D#B" },
 { msg: "The Loop Bounds", href: "/w03/D#C" },
 { msg: "The Bounds Precondition", href: "/w03/D#D" },
 { msg: "Advancing the Loop", href: "/w03/D#E" },
 { msg: "The Loop Goal", href: "/w03/D#F" },
 { msg: "Loop Operations", href: "/w03/D#G" },
 { msg: "The Loop Postcondition", href: "/w03/D#H" },
 { msg: "Loop Guards", href: "/w03/D#I" },
 { msg: "Necessary & Intentional", href: "/w03/D#J" },
 { msg: "Sentinel Loop Patters", href: "/w03/E#A" },
 { msg: "The Primed Loop Pattern", href: "/w03/E#B" },
 { msg: "The Loop-and-a-half Pattern", href: "/w03/E#C" },
 { msg: "The Flag-controlled Pattern", href: "/w03/E#D" },
 { msg: "Validating Data", href: "/w03/E#E" },
 { msg: "Library Mechanics", href: "/w04/A#A" },
 { msg: "Separate Compilation", href: "/w04/A#B" },
 { msg: "The Client or Test Program", href: "/w04/A#C" },
 { msg: "The Interface or Header File", href: "/w04/A#D" },
 { msg: "Adding the Prototypes", href: "/w04/A#E" },
 { msg: "Library Types in Interfaces", href: "/w04/A#F" },
 { msg: "The Implementation File", href: "/w04/A#G" },
 { msg: "Stubbing the Implementation", href: "/w04/A#H" },
 { msg: "The Make File", href: "/w04/A#I" },
 { msg: "Documenting the Interface", href: "/w04/B#A" },
 { msg: "Planning & Implementation", href: "/w04/B#B" },
 { msg: "The while Loop", href: "/w04/B#C" },
 { msg: "Limit Bounds", href: "/w04/B#D" },
 { msg: "Running Doxygen", href: "/w04/B#E" },
 { msg: "Overloaded Functions", href: "/w04/C#A" },
 { msg: "Overload Resolution", href: "/w04/C#B" },
 { msg: "Default Arguments", href: "/w04/C#C" },
 { msg: "Default Argument Rules", href: "/w04/C#D" },
 { msg: "Data Flows", href: "/w04/D#A" },
 { msg: "Output Parameters", href: "/w04/D#B" },
 { msg: "Input and Output Parameters", href: "/w04/D#C" },
 { msg: "Input-Output Parameters", href: "/w04/D#D" },
 { msg: "Data Flow Checklists", href: "/w04/D#E" },
 { msg: "More Selections & Iteration", href: "/w04/E#A" },
 { msg: "The switch Statement", href: "/w04/E#B" },
 { msg: "More on switch", href: "/w04/E#C" },
 { msg: "The Conditional Operator", href: "/w04/E#D" },
 { msg: "A Hasty Loop", href: "/w04/E#E" },
 { msg: "Confirmation Loops", href: "/w04/E#F" },
 { msg: "Introducing Recursion", href: "/w05/A#A" },
 { msg: "The Factorial Function", href: "/w05/A#B" },
 { msg: "A Recursive Example", href: "/w05/A#C" },
 { msg: "The Recursive Leap of Faith", href: "/w05/A#D" },
 { msg: "The Fibonacci Sequence", href: "/w05/A#E" },
 { msg: "Recursive Efficiency", href: "/w05/A#F" },
 { msg: "Efficient Recursion", href: "/w05/B#A" },
 { msg: "Wrappers & Helpers", href: "/w05/B#B" },
 { msg: "Checking Palindromes", href: "/w05/B#C" },
 { msg: "Palindrome Efficiency", href: "/w05/B#D" },
 { msg: "A Recursion Checklist I", href: "/w05/C#A" },
 { msg: "A Recursion Checklist II", href: "/w05/C#B" },
 { msg: "Code Step-by-Step", href: "/w05/C#C" },
 { msg: "Solving the Problem I", href: "/w05/C#D" },
 { msg: "Solving the Problem II", href: "/w05/C#E" },
 { msg: "The Standard Streams", href: "/w05/D#A" },
 { msg: "The cat Filter", href: "/w05/D#B" },
 { msg: "Input Redirection", href: "/w05/D#C" },
 { msg: "Output Redirection", href: "/w05/D#D" },
 { msg: "Error Redirection", href: "/w05/D#E" },
 { msg: "Pipes & Pipelines", href: "/w05/D#F" },
 { msg: "Built-in Filters", href: "/w05/D#G" },
 { msg: "Process Filters", href: "/w05/E#A" },
 { msg: "State Filters", href: "/w05/E#B" },
 { msg: "Your First Filter", href: "/w05/E#C" },
 { msg: "Data Loops", href: "/w05/E#D" },
 { msg: "More on Streams", href: "/w05/E#E" },
 { msg: "The Stream Classes", href: "/w06/A#A" },
 { msg: "UML Diagrams", href: "/w06/A#B" },
 { msg: "Easy File I/O", href: "/w06/A#C" },
 { msg: "Processing Lines", href: "/w06/A#D" },
 { msg: "Processing Tokens", href: "/w06/A#E" },
 { msg: "Applied File I/O", href: "/w06/B#A" },
 { msg: "Stub the Function", href: "/w06/B#B" },
 { msg: "Searching & Numbering", href: "/w06/B#C" },
 { msg: "Validating Data", href: "/w06/B#D" },
 { msg: "String Streams", href: "/w06/C#A" },
 { msg: "The format Function", href: "/w06/C#B" },
 { msg: "Input String Streams", href: "/w06/C#C" },
 { msg: "An Input Stream Exercise", href: "/w06/C#D" },
 { msg: "The Arguments", href: "/w06/C#E" },
 { msg: "The Longest Line", href: "/w06/C#F" },
 { msg: "Counting the Lines", href: "/w06/C#G" },
 { msg: "Processing the Tokens", href: "/w06/C#H" },
 { msg: "Conversion Functions", href: "/w06/D#A" },
 { msg: "Using the Functions", href: "/w06/D#B" },
 { msg: "Stub the Replacements", href: "/w06/D#C" },
 { msg: "Using #define", href: "/w06/D#D" },
 { msg: "Conditional Compilation", href: "/w06/D#E" },
 { msg: "Predefined Symbols", href: "/w06/D#F" },
 { msg: "Comparing the Results", href: "/w06/D#G" },
 { msg: "Handling Errors", href: "/w06/E#A" },
 { msg: "The Terminator", href: "/w06/E#B" },
 { msg: "Using assert", href: "/w06/E#C" },
 { msg: "More Assertions", href: "/w06/E#D" },
 { msg: "Completion Codes", href: "/w06/E#E" },
 { msg: "Error Flags", href: "/w06/E#F" },
 { msg: "Exception Handling", href: "/w07/A#A" },
 { msg: "Throwing Exceptions", href: "/w07/A#B" },
 { msg: "What Should You Throw?", href: "/w07/A#C" },
 { msg: "The try and catch Blocks", href: "/w07/A#D" },
 { msg: "Other catch Blocks", href: "/w07/A#E" },
 { msg: "The to_string Functions", href: "/w07/B#A" },
 { msg: "Function Templates", href: "/w07/B#B" },
 { msg: "Template Instantiation", href: "/w07/B#C" },
 { msg: "Template Argument Deduction", href: "/w07/B#D" },
 { msg: "Multiple Template Arguments", href: "/w07/B#E" },
 { msg: "Explicit Template Arguments", href: "/w07/B#F" },
 { msg: "Inferred Return Types", href: "/w07/B#G" },
 { msg: "Templates & Overloading", href: "/w07/B#H" },
 { msg: "Structured Types", href: "/w07/C#A" },
 { msg: "Structure Definitions", href: "/w07/C#B" },
 { msg: "Structure Variables", href: "/w07/C#C" },
 { msg: "Initialization", href: "/w07/C#D" },
 { msg: "Member Access", href: "/w07/C#E" },
 { msg: "Aggregate Operations", href: "/w07/C#F" },
 { msg: "Structure Arguments", href: "/w07/D#A" },
 { msg: "By-Value or By-Reference", href: "/w07/D#B" },
 { msg: "A Compare Function", href: "/w07/D#C" },
 { msg: "Returning Structures", href: "/w07/D#D" },
 { msg: "Structured Bindings", href: "/w07/D#E" },
 { msg: "Enumerated Types", href: "/w07/E#A" },
 { msg: "Defining Enumerated Types", href: "/w07/E#B" },
 { msg: "Enumerated Variables", href: "/w07/E#C" },
 { msg: "Enumerated Output", href: "/w07/E#D" },
 { msg: "Enumerated Input", href: "/w07/E#E" },
 { msg: "Why Vectors?", href: "/w08/A#A" },
 { msg: "Meet the vector", href: "/w08/A#B" },
 { msg: "Vector Variables", href: "/w08/A#C" },
 { msg: "Vector Initialization", href: "/w08/A#D" },
 { msg: "Element Access", href: "/w08/A#E" },
 { msg: "Range Checking", href: "/w08/A#F" },
 { msg: "Growing & Shrinking", href: "/w08/B#A" },
 { msg: "Vectors & Loops", href: "/w08/B#B" },
 { msg: "Common Algorithms", href: "/w08/B#C" },
 { msg: "Counting Algorithms", href: "/w08/B#D" },
 { msg: "Cumulative Algorithms", href: "/w08/B#E" },
 { msg: "Extreme Values", href: "/w08/B#F" },
 { msg: "Modifying Algorithms", href: "/w08/B#G" },
 { msg: "Filling & Shuffling", href: "/w08/B#H" },
 { msg: "Vectors & Functions", href: "/w08/B#I" },
 { msg: "Memory & Addresses", href: "/w08/C#A" },
 { msg: "Naming Concepts", href: "/w08/C#B" },
 { msg: "Global Variables", href: "/w08/C#C" },
 { msg: "Local Variables", href: "/w08/C#D" },
 { msg: "Characteristics of Variables", href: "/w08/C#E" },
 { msg: "The sizeof Operator", href: "/w08/C#F" },
 { msg: "The Address Operator", href: "/w08/C#G" },
 { msg: "Pointers", href: "/w08/D#A" },
 { msg: "Defining Pointers", href: "/w08/D#B" },
 { msg: "Initializing Pointers", href: "/w08/D#C" },
 { msg: "Dereferencing Pointers", href: "/w08/D#D" },
 { msg: "Pointer Assignment", href: "/w08/D#E" },
 { msg: 'The "null" Pointer', href: "/w08/D#F" },
 { msg: "Digital Images", href: "/w08/E#A" },
 { msg: "RGB Colors", href: "/w08/E#B" },
 { msg: "The RGB Explorer", href: "/w08/E#C" },
 { msg: "Digital Images in C++", href: "/w08/E#D" },
 { msg: "Loading an Image", href: "/w08/E#E" },
 { msg: "More on Loading an Image", href: "/w08/E#F" },
 { msg: "Saving an Image", href: "/w08/E#G" },
 { msg: "Changing the Format", href: "/w08/E#H" },
 { msg: "Digital Filters", href: "/w09/A#A" },
 { msg: "Address Arithmetic", href: "/w09/A#B" },
 { msg: "Iterator Loops", href: "/w09/A#C" },
 { msg: "The Darken Filter", href: "/w09/A#D" },
 { msg: "Dealing with Channels", href: "/w09/A#E" },
 { msg: "State Filters", href: "/w09/A#F" },
 { msg: "Pointers & Structures", href: "/w09/A#G" },
 { msg: "Using reinterpret_cast", href: "/w09/A#H" },
 { msg: "Introducing Arrays", href: "/w09/B#A" },
 { msg: "Array vs. vector", href: "/w09/B#B" },
 { msg: "Defining Arrays", href: "/w09/B#C" },
 { msg: "Array Initialization", href: "/w09/B#D" },
 { msg: "The Allocated Size", href: "/w09/B#E" },
 { msg: "Array Selection", href: "/w09/B#F" },
 { msg: "Characteristics of Arrays", href: "/w09/B#G" },
 { msg: "Pointers & Arrays", href: "/w09/C#A" },
 { msg: "Pointer Arithmetic & Arrays", href: "/w09/C#B" },
 { msg: "Dereferencing Arrays", href: "/w09/C#C" },
 { msg: "Arrays & Functions", href: "/w09/C#D" },
 { msg: "Decaying Arrays", href: "/w09/C#E" },
 { msg: "Arrays & Const", href: "/w09/C#F" },
 { msg: "Arrays and Loops", href: "/w09/D#A" },
 { msg: "Counter-Controlled Loops", href: "/w09/D#B" },
 { msg: "Sentinel Loops", href: "/w09/D#C" },
 { msg: "Iterator Loops", href: "/w09/D#D" },
 { msg: "A C++ Idiom", href: "/w09/D#E" },
 { msg: "Arrays and Algorithms", href: "/w09/E#A" },
 { msg: "Counting Algorithms", href: "/w09/E#B" },
 { msg: "Cumulative Algorithms", href: "/w09/E#C" },
 { msg: "Extreme Values", href: "/w09/E#D" },
 { msg: "Returning a Pointer", href: "/w09/E#E" },
 { msg: "Returning an Index", href: "/w09/E#F" },
 { msg: "The Fencepost Algorithm", href: "/w09/E#G" },
 { msg: "A Reverse Fencepost", href: "/w09/E#H" },
 { msg: "Searching Algorithms", href: "/w10/A#A" },
 { msg: "The Starter Code", href: "/w10/A#B" },
 { msg: "The find() Function", href: "/w10/A#C" },
 { msg: "Linear Search", href: "/w10/A#D" },
 { msg: "Linear Search Efficiency", href: "/w10/A#E" },
 { msg: "Improving Linear Search", href: "/w10/A#F" },
 { msg: "Binary Search", href: "/w10/A#G" },
 { msg: "Implementing Binary Search", href: "/w10/A#H" },
 { msg: "An Array Example", href: "/w10/B#A" },
 { msg: "Appending Elements", href: "/w10/B#B" },
 { msg: "Traversing the Array", href: "/w10/B#C" },
 { msg: "Inserting Elements", href: "/w10/B#D" },
 { msg: "Applying the Algorithm", href: "/w10/B#E" },
 { msg: "Removing Elements", href: "/w10/B#F" },
 { msg: "Removing Multiple Elements", href: "/w10/B#G" },
 { msg: "2D Arrays", href: "/w10/C#A" },
 { msg: "Row Major Order", href: "/w10/C#B" },
 { msg: "2D Array Initialization", href: "/w10/C#C" },
 { msg: "2D Arrays & Functions", href: "/w10/C#D" },
 { msg: "C-Style Strings", href: "/w10/D#A" },
 { msg: "C-String Basics", href: "/w10/D#B" },
 { msg: "Array-based C-Strings", href: "/w10/D#C" },
 { msg: "Pointer-based C-Strings", href: "/w10/D#D" },
 { msg: "C++ Strings vs. C-Strings", href: "/w10/D#E" },
 { msg: "C-String Assignment", href: "/w10/D#F" },
 { msg: "The strncpy Function", href: "/w10/D#G" },
 { msg: "The strcat Functions", href: "/w10/D#H" },
 { msg: "Comparing C-Strings", href: "/w10/D#I" },
 { msg: "The strlen Function", href: "/w10/E#A" },
 { msg: "The strcpy Function", href: "/w10/E#B" },
 { msg: "The strcmp Function", href: "/w10/E#C" },
 { msg: "Writing Your Own Functions", href: "/w10/E#D" },
 { msg: "Find First", href: "/w10/E#E" },
 { msg: "Find Last", href: "/w10/E#F" },
 { msg: "Find First of Any", href: "/w10/E#G" },
 { msg: "Finding Substrings", href: "/w10/E#H" },
 { msg: "The Shell", href: "/w11/A#A" },
 { msg: "The Command Line", href: "/w11/A#B" },
 { msg: "Command-Line Arguments", href: "/w11/A#C" },
 { msg: "Using Command-Line Arguments", href: "/w11/A#D" },
 { msg: "Traversing the Arguments", href: "/w11/A#E" },
 { msg: "Converting Arguments", href: "/w11/A#F" },
 { msg: "Introducing the Heap", href: "/w11/B#A" },
 { msg: "Stack vs. Heap", href: "/w11/B#B" },
 { msg: "The new Operator", href: "/w11/B#C" },
 { msg: "Dyanmic Arrays", href: "/w11/B#D" },
 { msg: "Dynamic Objects", href: "/w11/B#E" },
 { msg: "Freeing Memory", href: "/w11/B#F" },
 { msg: "Memory Management", href: "/w11/C#A" },
 { msg: "Memory Leaks", href: "/w11/C#B" },
 { msg: "Dangling Pointers", href: "/w11/C#C" },
 { msg: "Double Deletes", href: "/w11/C#D" },
 { msg: "Smart Pointers", href: "/w11/C#E" },
 { msg: "Shared Pointers", href: "/w11/C#F" },
 { msg: "Unique Pointers", href: "/w11/C#G" },
 { msg: "Smart Pointers & Functions", href: "/w11/C#H" },
 { msg: "Unique Pointers and Containers", href: "/w11/C#I" },
 { msg: "Unique Pointers and Dynamic Arrays", href: "/w11/C#J" },
 { msg: "The Iron Age", href: "/w11/D#A" },
 { msg: "User-Defined Types", href: "/w11/D#B" },
 { msg: "Object-Based Programming", href: "/w11/D#C" },
 { msg: "Time as a Structure", href: "/w11/D#D" },
 { msg: "Type Invariants", href: "/w11/D#E" },
 { msg: "A Scenario", href: "/w11/D#F" },
 { msg: "The Problem", href: "/w11/D#G" },
 { msg: "Information Hiding", href: "/w11/E#A" },
 { msg: "The Public Interface", href: "/w11/E#B" },
 { msg: "Member Functions", href: "/w11/E#C" },
 { msg: "Proving the Interface", href: "/w11/E#D" },
 { msg: "The Implementation File", href: "/w11/E#E" },
 { msg: "Implementing Member Functions", href: "/w11/E#F" },
 { msg: "Introducing OOP", href: "/w12/A#A" },
 { msg: "What are Objects", href: "/w12/A#B" },
 { msg: "State and Behavior", href: "/w12/A#C" },
 { msg: "What are Classes", href: "/w12/A#D" },
 { msg: "What is Encapsulation", href: "/w12/A#E" },
 { msg: "Real World Encapsulation", href: "/w12/A#F" },
 { msg: "The Wall of Abstraction", href: "/w12/B#A" },
 { msg: "Class Definition Syntax", href: "/w12/B#B" },
 { msg: "Public and Private", href: "/w12/B#C" },
 { msg: "The Implicit Parameter", href: "/w12/B#D" },
 { msg: "The Pointer this", href: "/w12/B#E" },
 { msg: "The sum Member Function", href: "/w12/B#F" },
 { msg: "Setters", href: "/w12/C#A" },
 { msg: "Getter & Setter Patterns", href: "/w12/C#B" },
 { msg: "Constructors", href: "/w12/C#C" },
 { msg: "Member Initialization", href: "/w12/C#D" },
 { msg: "Working Constructor", href: "/w12/C#E" },
 { msg: "Assignment vs. Initialization", href: "/w12/C#F" },
 { msg: "The Initializer List", href: "/w12/C#G" },
 { msg: "The Working Constructor", href: "/w12/D#A" },
 { msg: "Conversion Constructors", href: "/w12/D#B" },
 { msg: "Implicit vs. Explicit", href: "/w12/D#C" },
 { msg: "Assign, Copy & Destroy", href: "/w12/D#D" },
 { msg: "Static Data Members", href: "/w12/D#E" },
 { msg: "Static Member Functions", href: "/w12/D#F" },
 { msg: "static const Data Members", href: "/w12/D#G" },
 { msg: "Classification", href: "/w12/E#A" },
 { msg: "Inheritance", href: "/w12/E#B" },
 { msg: "Person <- Student", href: "/w12/E#C" },
 { msg: "The UML Diagram", href: "/w12/E#D" },
 { msg: "Inherited Members", href: "/w12/E#E" },
 { msg: "Private Base-class Members", href: "/w12/E#F" },
 { msg: "Base-class Constructors", href: "/w13/A#A" },
 { msg: "Derived-class Constructors", href: "/w13/A#B" },
 { msg: "Constructor Chaining", href: "/w13/A#C" },
 { msg: "Default Constructors", href: "/w13/A#D" },
 { msg: "Calling the Base Constructor", href: "/w13/A#E" },
 { msg: "Protected Members", href: "/w13/A#F" },
 { msg: "Virtual Member Functions", href: "/w13/B#A" },
 { msg: "Implementing toString()", href: "/w13/B#B" },
 { msg: "Overriding toString()", href: "/w13/B#C" },
 { msg: "Implementing Student::toString()", href: "/w13/B#D" },
 { msg: "Combining toString()", href: "/w13/B#E" },
 { msg: "The override Keyword", href: "/w13/B#F" },
 { msg: "The Stream Class Hierarchy", href: "/w13/B#G" },
 { msg: "Stream Substitutability", href: "/w13/B#H" },
 { msg: "Substitution vs. Conversion", href: "/w13/B#I" },
 { msg: "Class Relationships", href: "/w13/C#A" },
 { msg: "Polymorphic Inheritance", href: "/w13/C#B" },
 { msg: "Static Polymorphism", href: "/w13/C#C" },
 { msg: "A Perplexing Problem", href: "/w13/C#D" },
 { msg: "The Slicing Problem", href: "/w13/C#E" },
 { msg: "References & Pointers", href: "/w13/C#F" },
 { msg: "Polymorphic Functions", href: "/w13/C#G" },
 { msg: "Polymorphic Lists", href: "/w13/C#H" },
 { msg: "Pointers to the Rescue?", href: "/w13/C#I" },
 { msg: "Maybe Smart Pointers", href: "/w13/C#J" },
 { msg: "Early & Late Binding", href: "/w13/D#A" },
 { msg: "How Late Binding Works", href: "/w13/D#B" },
 { msg: "Multiple Inheritance", href: "/w13/D#C" },
 { msg: "Contraction", href: "/w13/D#D" },
 { msg: "Private Inheritance", href: "/w13/D#E" },
 { msg: "Composition", href: "/w13/D#F" },
 { msg: "Specification Inheritance", href: "/w13/E#A" },
 { msg: "Abstract Classes", href: "/w13/E#B" },
 { msg: "Creating an Abstract Class", href: "/w13/E#C" },
 { msg: "Using an Abstract Class", href: "/w13/E#D" },
 { msg: "A Triangle Example", href: "/w13/E#E" },
 { msg: "Redefining Functions", href: "/w13/E#F" },
 { msg: "Final Classes", href: "/w13/E#G" },
];

export default chapters;
