const chapters = [
 {
  msg: "An Overview of C++",
  href: "/w01/A#A",
  heading: "A-An Overview of C++",
 },
 {
  msg: "The C++ Programming Language",
  href: "/w01/A#B",
  heading: "A-An Overview of C++",
 },
 {
  msg: "Hello World",
  href: "/w01/A#C",
  heading: "A-An Overview of C++",
 },
 {
  msg: "Source Code",
  href: "/w01/A#D",
  heading: "A-An Overview of C++",
 },
 {
  msg: "Program Mechanics",
  href: "/w01/A#E",
  heading: "A-An Overview of C++",
 },
 {
  msg: "The Build Process",
  href: "/w01/A#F",
  heading: "A-An Overview of C++",
 },
 {
  msg: "Early Computing",
  href: "/w01/B#A",
  heading: "B-The C++ Back Story",
 },
 {
  msg: "Machine Language",
  href: "/w01/B#B",
  heading: "B-The C++ Back Story",
 },
 {
  msg: "High-Level Languages",
  href: "/w01/B#C",
  heading: "B-The C++ Back Story",
 },
 {
  msg: "The C Language",
  href: "/w01/B#D",
  heading: "B-The C++ Back Story",
 },
 {
  msg: "Object-Oriented Programming",
  href: "/w01/B#E",
  heading: "B-The C++ Back Story",
 },
 {
  msg: "The C++ Language",
  href: "/w01/B#F",
  heading: "B-The C++ Back Story",
 },
 { msg: "C++ Syntax", href: "/w01/C#A", heading: "C-Syntax Basics" },
 { msg: "The f2c Program", href: "/w01/C#B", heading: "C-Syntax Basics" },
 {
  msg: "The Standard C++ Library",
  href: "/w01/C#C",
  heading: "C-Syntax Basics",
 },
 {
  msg: "The main Function",
  href: "/w01/C#D",
  heading: "C-Syntax Basics",
 },
 {
  msg: "The convert Function",
  href: "/w01/C#E",
  heading: "C-Syntax Basics",
 },
 { msg: "Variables", href: "/w01/D#A", heading: "D-Variables & Values" },
 {
  msg: "Definitions & Types",
  href: "/w01/D#B",
  heading: "D-Variables & Values",
 },
 {
  msg: "Identifiers & Constants",
  href: "/w01/D#C",
  heading: "D-Variables & Values",
 },
 {
  msg: "The Initialization",
  href: "/w01/D#D",
  heading: "D-Variables & Values",
 },
 { msg: "Assignment", href: "/w01/D#E", heading: "D-Variables & Values" },
 {
  msg: "Console Output",
  href: "/w01/D#F",
  heading: "D-Variables & Values",
 },
 {
  msg: "Console Input",
  href: "/w01/D#G",
  heading: "D-Variables & Values",
 },
 {
  msg: "Integers",
  href: "/w01/E#A",
  heading: "E-Numbers & Calculations",
 },
 {
  msg: "Signed & Unsigned",
  href: "/w01/E#B",
  heading: "E-Numbers & Calculations",
 },
 {
  msg: "Integer Literals",
  href: "/w01/E#C",
  heading: "E-Numbers & Calculations",
 },
 {
  msg: "Floating-point Numbers",
  href: "/w01/E#D",
  heading: "E-Numbers & Calculations",
 },
 {
  msg: "Floating-point Output",
  href: "/w01/E#E",
  heading: "E-Numbers & Calculations",
 },
 {
  msg: "Expressions",
  href: "/w01/E#F",
  heading: "E-Numbers & Calculations",
 },
 {
  msg: "Expression Evaluation",
  href: "/w01/E#G",
  heading: "E-Numbers & Calculations",
 },
 {
  msg: "Integer Division & Remainders",
  href: "/w02/A#A",
  heading: "A-Side-Effect Operators",
 },
 {
  msg: "Assignment Operators",
  href: "/w02/A#B",
  heading: "A-Side-Effect Operators",
 },
 {
  msg: "Increment and Decrement",
  href: "/w02/A#C",
  heading: "A-Side-Effect Operators",
 },
 {
  msg: "Mixed-type Expressions",
  href: "/w02/A#D",
  heading: "A-Side-Effect Operators",
 },
 {
  msg: "Type Casts",
  href: "/w02/A#E",
  heading: "A-Side-Effect Operators",
 },
 {
  msg: "Functions",
  href: "/w02/A#F",
  heading: "A-Side-Effect Operators",
 },
 {
  msg: "The <cmath > Header",
  href: "/w02/A#G",
  heading: "A-Side-Effect Operators",
 },
 {
  msg: "Writing Functions",
  href: "/w02/B#A",
  heading: "B-Functions & Decomposition",
 },
 {
  msg: "Function Syntax",
  href: "/w02/B#B",
  heading: "B-Functions & Decomposition",
 },
 {
  msg: "The Function Body",
  href: "/w02/B#C",
  heading: "B-Functions & Decomposition",
 },
 {
  msg: "Functional Decomposition",
  href: "/w02/B#D",
  heading: "B-Functions & Decomposition",
 },
 {
  msg: "Declaring & Defining",
  href: "/w02/B#E",
  heading: "B-Functions & Decomposition",
 },
 {
  msg: "Making Decisions",
  href: "/w02/C#A",
  heading: "C-Making Decisions",
 },
 {
  msg: "Blocks, Style & Indentation",
  href: "/w02/C#B",
  heading: "C-Making Decisions",
 },
 {
  msg: "The bool Data Type",
  href: "/w02/C#C",
  heading: "C-Making Decisions",
 },
 {
  msg: "The Relational Operatorrs",
  href: "/w02/C#D",
  heading: "C-Making Decisions",
 },
 {
  msg: "The Logical Operators",
  href: "/w02/C#E",
  heading: "C-Making Decisions",
 },
 {
  msg: "Multi-way Branching",
  href: "/w02/C#F",
  heading: "C-Making Decisions",
 },
 {
  msg: "Nested if Statements",
  href: "/w02/C#G",
  heading: "C-Making Decisions",
 },
 {
  msg: "Creating String Object",
  href: "/w02/D#A",
  heading: "D-C++ Strings",
 },
 {
  msg: "String Input and Output",
  href: "/w02/D#B",
  heading: "D-C++ Strings",
 },
 {
  msg: "Concatenation & Comparison",
  href: "/w02/D#C",
  heading: "D-C++ Strings",
 },
 {
  msg: "Mutability & Value Assignment",
  href: "/w02/D#D",
  heading: "D-C++ Strings",
 },
 { msg: "Member Function", href: "/w02/D#E", heading: "D-C++ Strings" },
 {
  msg: "String Members",
  href: "/w02/E#A",
  heading: "E-Processing Strings",
 },
 { msg: "Characters", href: "/w02/E#B", heading: "E-Processing Strings" },
 {
  msg: "Selecting Characters",
  href: "/w02/E#C",
  heading: "E-Processing Strings",
 },
 { msg: "Substrings", href: "/w02/E#D", heading: "E-Processing Strings" },
 {
  msg: "Searching a String",
  href: "/w02/E#E",
  heading: "E-Processing Strings",
 },
 { msg: "References", href: "/w03/A#A", heading: "A-Reference Types" },
 {
  msg: "Conversions & Const-ref",
  href: "/w03/A#B",
  heading: "A-Reference Types",
 },
 {
  msg: "Reference Parameters",
  href: "/w03/A#C",
  heading: "A-Reference Types",
 },
 {
  msg: "String Value Parameters",
  href: "/w03/A#D",
  heading: "A-Reference Types",
 },
 {
  msg: "String Reference Parameters",
  href: "/w03/A#E",
  heading: "A-Reference Types",
 },
 {
  msg: "Introducing Loops",
  href: "/w03/B#A",
  heading: "B-Introducing Loops",
 },
 {
  msg: "Guarded & Unguarded Loops",
  href: "/w03/B#B",
  heading: "B-Introducing Loops",
 },
 {
  msg: "Classifying Loops",
  href: "/w03/B#C",
  heading: "B-Introducing Loops",
 },
 {
  msg: "Indefinite Loop Categories",
  href: "/w03/B#D",
  heading: "B-Introducing Loops",
 },
 {
  msg: "Range-based Loops",
  href: "/w03/B#E",
  heading: "B-Introducing Loops",
 },
 {
  msg: "Definite Loops with for",
  href: "/w03/C#A",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "Sequences & Symmetric Bounds",
  href: "/w03/C#B",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "Processing Strings",
  href: "/w03/C#C",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "Some Bad Habits",
  href: "/w03/C#D",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "Hands On: Counting Vowels",
  href: "/w03/C#E",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "Hands On: Counting Substrings",
  href: "/w03/C#F",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "More Efficient Substrings",
  href: "/w03/C#G",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "Substrings Redux",
  href: "/w03/C#H",
  heading: "C-Definite Loops with For",
 },
 {
  msg: "Goal, Bounds & Plan",
  href: "/w03/D#A",
  heading: "D-How to Write Loops",
 },
 {
  msg: "Implement the Plan",
  href: "/w03/D#B",
  heading: "D-How to Write Loops",
 },
 {
  msg: "The Loop Bounds",
  href: "/w03/D#C",
  heading: "D-How to Write Loops",
 },
 {
  msg: "The Bounds Precondition",
  href: "/w03/D#D",
  heading: "D-How to Write Loops",
 },
 {
  msg: "Advancing the Loop",
  href: "/w03/D#E",
  heading: "D-How to Write Loops",
 },
 {
  msg: "The Loop Goal",
  href: "/w03/D#F",
  heading: "D-How to Write Loops",
 },
 {
  msg: "Loop Operations",
  href: "/w03/D#G",
  heading: "D-How to Write Loops",
 },
 {
  msg: "The Loop Postcondition",
  href: "/w03/D#H",
  heading: "D-How to Write Loops",
 },
 {
  msg: "Loop Guards",
  href: "/w03/D#I",
  heading: "D-How to Write Loops",
 },
 {
  msg: "Necessary & Intentional",
  href: "/w03/D#J",
  heading: "D-How to Write Loops",
 },
 {
  msg: "Sentinel Loop Patters",
  href: "/w03/E#A",
  heading: "E-Sentinel Loop Patterns",
 },
 {
  msg: "The Primed Loop Pattern",
  href: "/w03/E#B",
  heading: "E-Sentinel Loop Patterns",
 },
 {
  msg: "The Loop-and-a-half Pattern",
  href: "/w03/E#C",
  heading: "E-Sentinel Loop Patterns",
 },
 {
  msg: "The Flag-controlled Pattern",
  href: "/w03/E#D",
  heading: "E-Sentinel Loop Patterns",
 },
 {
  msg: "Validating Data",
  href: "/w03/E#E",
  heading: "E-Sentinel Loop Patterns",
 },
 {
  msg: "Library Mechanics",
  href: "/w04/A#A",
  heading: "A-Library Mechanics",
 },
 {
  msg: "Separate Compilation",
  href: "/w04/A#B",
  heading: "A-Library Mechanics",
 },
 {
  msg: "The Client or Test Program",
  href: "/w04/A#C",
  heading: "A-Library Mechanics",
 },
 {
  msg: "The Interface or Header File",
  href: "/w04/A#D",
  heading: "A-Library Mechanics",
 },
 {
  msg: "Adding the Prototypes",
  href: "/w04/A#E",
  heading: "A-Library Mechanics",
 },
 {
  msg: "Library Types in Interfaces",
  href: "/w04/A#F",
  heading: "A-Library Mechanics",
 },
 {
  msg: "Implementation File",
  href: "/w04/A#G",
  heading: "A-Library Mechanics",
 },
 {
  msg: "Stubbing the Implementation",
  href: "/w04/A#H",
  heading: "A-Library Mechanics",
 },
 {
  msg: "The Make File",
  href: "/w04/A#I",
  heading: "A-Library Mechanics",
 },
 {
  msg: "Documenting the Interface",
  href: "/w04/B#A",
  heading: "B-Documentation & Implementation",
 },
 {
  msg: "Planning & Implementation",
  href: "/w04/B#B",
  heading: "B-Documentation & Implementation",
 },
 {
  msg: "The while Loop",
  href: "/w04/B#C",
  heading: "B-Documentation & Implementation",
 },
 {
  msg: "Limit Bounds",
  href: "/w04/B#D",
  heading: "B-Documentation & Implementation",
 },
 {
  msg: "Running Doxygen",
  href: "/w04/B#E",
  heading: "B-Documentation & Implementation",
 },
 {
  msg: "Overloaded Functions",
  href: "/w04/C#A",
  heading: "C-Overloading & Default Arguments",
 },
 {
  msg: "Overload Resolution",
  href: "/w04/C#B",
  heading: "C-Overloading & Default Arguments",
 },
 {
  msg: "Default Arguments",
  href: "/w04/C#C",
  heading: "C-Overloading & Default Arguments",
 },
 {
  msg: "Default Argument Rules",
  href: "/w04/C#D",
  heading: "C-Overloading & Default Arguments",
 },
 { msg: "Data Flows", href: "/w04/D#A", heading: "D-Data Flows" },
 { msg: "Output Parameters", href: "/w04/D#B", heading: "D-Data Flows" },
 {
  msg: "Input and Output Parameters",
  href: "/w04/D#C",
  heading: "D-Data Flows",
 },
 {
  msg: "Input-Output Parameters",
  href: "/w04/D#D",
  heading: "D-Data Flows",
 },
 {
  msg: "Data Flow Checklists",
  href: "/w04/D#E",
  heading: "D-Data Flows",
 },
 {
  msg: "More Selections & Iteration",
  href: "/w04/E#A",
  heading: "E-More Selections & Iteration",
 },
 {
  msg: "The switch Statement",
  href: "/w04/E#B",
  heading: "E-More Selections & Iteration",
 },
 {
  msg: "More on switch",
  href: "/w04/E#C",
  heading: "E-More Selections & Iteration",
 },
 {
  msg: "The Conditional Operator",
  href: "/w04/E#D",
  heading: "E-More Selections & Iteration",
 },
 {
  msg: "A Hasty Loop",
  href: "/w04/E#E",
  heading: "E-More Selections & Iteration",
 },
 {
  msg: "Confirmation Loops",
  href: "/w04/E#F",
  heading: "E-More Selections & Iteration",
 },
 {
  msg: "Introducing Recursion",
  href: "/w05/A#A",
  heading: "A-Introducing Recursion",
 },
 {
  msg: "The Factorial Function",
  href: "/w05/A#B",
  heading: "A-Introducing Recursion",
 },
 {
  msg: "A Recursive Example",
  href: "/w05/A#C",
  heading: "A-Introducing Recursion",
 },
 {
  msg: "The Recursive Leap of Faith",
  href: "/w05/A#D",
  heading: "A-Introducing Recursion",
 },
 {
  msg: "The Fibonacci Sequence",
  href: "/w05/A#E",
  heading: "A-Introducing Recursion",
 },
 {
  msg: "Recursive Efficiency",
  href: "/w05/A#F",
  heading: "A-Introducing Recursion",
 },
 {
  msg: "Efficient Recursion",
  href: "/w05/B#A",
  heading: "B-Efficient Recursion",
 },
 {
  msg: "Wrappers & Helpers",
  href: "/w05/B#B",
  heading: "B-Efficient Recursion",
 },
 {
  msg: "Checking Palindromes",
  href: "/w05/B#C",
  heading: "B-Efficient Recursion",
 },
 {
  msg: "Palindrome Efficiency",
  href: "/w05/B#D",
  heading: "B-Efficient Recursion",
 },
 {
  msg: "A Recursion Checklist I",
  href: "/w05/C#A",
  heading: "C-Applying Recursion",
 },
 {
  msg: "A Recursion Checklist II",
  href: "/w05/C#B",
  heading: "C-Applying Recursion",
 },
 {
  msg: "Code Step-by-Step",
  href: "/w05/C#C",
  heading: "C-Applying Recursion",
 },
 {
  msg: "Solving the Problem I",
  href: "/w05/C#D",
  heading: "C-Applying Recursion",
 },
 {
  msg: "Solving the Problem II",
  href: "/w05/C#E",
  heading: "C-Applying Recursion",
 },
 {
  msg: "The Standard Streams",
  href: "/w05/D#A",
  heading: "D-Streams & Redirection",
 },
 {
  msg: "The cat Filter",
  href: "/w05/D#B",
  heading: "D-Streams & Redirection",
 },
 {
  msg: "Input Redirection",
  href: "/w05/D#C",
  heading: "D-Streams & Redirection",
 },
 {
  msg: "Output Redirection",
  href: "/w05/D#D",
  heading: "D-Streams & Redirection",
 },
 {
  msg: "Error Redirection",
  href: "/w05/D#E",
  heading: "D-Streams & Redirection",
 },
 {
  msg: "Pipes & Pipelines",
  href: "/w05/D#F",
  heading: "D-Streams & Redirection",
 },
 {
  msg: "Built-in Filters",
  href: "/w05/D#G",
  heading: "D-Streams & Redirection",
 },
 { msg: "Process Filters", href: "/w05/E#A", heading: "E-Filters" },
 { msg: "State Filters", href: "/w05/E#B", heading: "E-Filters" },
 { msg: "Your First Filter", href: "/w05/E#C", heading: "E-Filters" },
 { msg: "Data Loops", href: "/w05/E#D", heading: "E-Filters" },
 { msg: "More on Streams", href: "/w05/E#E", heading: "E-Filters" },
 {
  msg: "The Stream Classes",
  href: "/w06/A#A",
  heading: "A-Processing Files",
 },
 { msg: "UML Diagrams", href: "/w06/A#B", heading: "A-Processing Files" },
 {
  msg: "Easy File I/O",
  href: "/w06/A#C",
  heading: "A-Processing Files",
 },
 {
  msg: "Processing Lines",
  href: "/w06/A#D",
  heading: "A-Processing Files",
 },
 {
  msg: "Processing Tokens",
  href: "/w06/A#E",
  heading: "A-Processing Files",
 },
 {
  msg: "Applied File I/O",
  href: "/w06/B#A",
  heading: "B-Validating Data",
 },
 {
  msg: "Stub the Function",
  href: "/w06/B#B",
  heading: "B-Validating Data",
 },
 {
  msg: "Searching & Numbering",
  href: "/w06/B#C",
  heading: "B-Validating Data",
 },
 {
  msg: "Validate Data",
  href: "/w06/B#D",
  heading: "B-Validating Data",
 },
 { msg: "String Streams", href: "/w06/C#A", heading: "C-String Streams" },
 {
  msg: "The format Function",
  href: "/w06/C#B",
  heading: "C-String Streams",
 },
 {
  msg: "Input String Streams",
  href: "/w06/C#C",
  heading: "C-String Streams",
 },
 {
  msg: "An Input Stream Exercise",
  href: "/w06/C#D",
  heading: "C-String Streams",
 },
 { msg: "The Arguments", href: "/w06/C#E", heading: "C-String Streams" },
 {
  msg: "The Longest Line",
  href: "/w06/C#F",
  heading: "C-String Streams",
 },
 {
  msg: "Counting the Lines",
  href: "/w06/C#G",
  heading: "C-String Streams",
 },
 {
  msg: "Processing the Tokens",
  href: "/w06/C#H",
  heading: "C-String Streams",
 },
 {
  msg: "Conversion Functions",
  href: "/w06/D#A",
  heading: "D-Conditional Compilation",
 },
 {
  msg: "Using the Functions",
  href: "/w06/D#B",
  heading: "D-Conditional Compilation",
 },
 {
  msg: "Stub the Replacements",
  href: "/w06/D#C",
  heading: "D-Conditional Compilation",
 },
 {
  msg: "Using #define",
  href: "/w06/D#D",
  heading: "D-Conditional Compilation",
 },
 {
  msg: "Conditional Compilation",
  href: "/w06/D#E",
  heading: "D-Conditional Compilation",
 },
 {
  msg: "Predefined Symbols",
  href: "/w06/D#F",
  heading: "D-Conditional Compilation",
 },
 {
  msg: "Comparing the Results",
  href: "/w06/D#G",
  heading: "D-Conditional Compilation",
 },
 {
  msg: "Handling Errors",
  href: "/w06/E#A",
  heading: "E-Errors & Assertions",
 },
 {
  msg: "The Terminator",
  href: "/w06/E#B",
  heading: "E-Errors & Assertions",
 },
 {
  msg: "Using assert",
  href: "/w06/E#C",
  heading: "E-Errors & Assertions",
 },
 {
  msg: "More Assertions",
  href: "/w06/E#D",
  heading: "E-Errors & Assertions",
 },
 {
  msg: "Completion Codes",
  href: "/w06/E#E",
  heading: "E-Errors & Assertions",
 },
 {
  msg: "Error Flags",
  href: "/w06/E#F",
  heading: "E-Errors & Assertions",
 },
 {
  msg: "Exception Handling",
  href: "/w07/A#A",
  heading: "A-Exception Handling",
 },
 {
  msg: "Throwing Exceptions",
  href: "/w07/A#B",
  heading: "A-Exception Handling",
 },
 {
  msg: "What Should You Throw?",
  href: "/w07/A#C",
  heading: "A-Exception Handling",
 },
 {
  msg: "The try and catch Blocks",
  href: "/w07/A#D",
  heading: "A-Exception Handling",
 },
 {
  msg: "Other catch Blocks",
  href: "/w07/A#E",
  heading: "A-Exception Handling",
 },
 {
  msg: "The to_string Functions",
  href: "/w07/B#A",
  heading: "B-Templates",
 },
 { msg: "Function Templates", href: "/w07/B#B", heading: "B-Templates" },
 {
  msg: "Template Instantiation",
  href: "/w07/B#C",
  heading: "B-Templates",
 },
 {
  msg: "Template Argument Deduction",
  href: "/w07/B#D",
  heading: "B-Templates",
 },
 {
  msg: "Multiple Template Arguments",
  href: "/w07/B#E",
  heading: "B-Templates",
 },
 {
  msg: "Explicit Template Arguments",
  href: "/w07/B#F",
  heading: "B-Templates",
 },
 {
  msg: "Inferred Return Types",
  href: "/w07/B#G",
  heading: "B-Templates",
 },
 {
  msg: "Templates & Overloading",
  href: "/w07/B#H",
  heading: "B-Templates",
 },
 {
  msg: "Structured Types",
  href: "/w07/C#A",
  heading: "C-Structured Types",
 },
 {
  msg: "Structure Definitions",
  href: "/w07/C#B",
  heading: "C-Structured Types",
 },
 {
  msg: "Structure Variables",
  href: "/w07/C#C",
  heading: "C-Structured Types",
 },
 {
  msg: "Initialization",
  href: "/w07/C#D",
  heading: "C-Structured Types",
 },
 {
  msg: "Member Access",
  href: "/w07/C#E",
  heading: "C-Structured Types",
 },
 {
  msg: "Aggregate Operations",
  href: "/w07/C#F",
  heading: "C-Structured Types",
 },
 {
  msg: "Structure Arguments",
  href: "/w07/D#A",
  heading: "D-Structures & Functions",
 },
 {
  msg: "By-Value or By-Reference",
  href: "/w07/D#B",
  heading: "D-Structures & Functions",
 },
 {
  msg: "A Compare Function",
  href: "/w07/D#C",
  heading: "D-Structures & Functions",
 },
 {
  msg: "Returning Structures",
  href: "/w07/D#D",
  heading: "D-Structures & Functions",
 },
 {
  msg: "Structured Bindings",
  href: "/w07/D#E",
  heading: "D-Structures & Functions",
 },
 {
  msg: "Enumerated Types",
  href: "/w07/E#A",
  heading: "E-Enumerated Types",
 },
 {
  msg: "Defining Enumerated Types",
  href: "/w07/E#B",
  heading: "E-Enumerated Types",
 },
 {
  msg: "Enumerated Variables",
  href: "/w07/E#C",
  heading: "E-Enumerated Types",
 },
 {
  msg: "Enumerated Output",
  href: "/w07/E#D",
  heading: "E-Enumerated Types",
 },
 {
  msg: "Enumerated Input",
  href: "/w07/E#E",
  heading: "E-Enumerated Types",
 },
 { msg: "Why Vectors?", href: "/w08/A#A", heading: "A-The vector Type" },
 {
  msg: "Meet the vector",
  href: "/w08/A#B",
  heading: "A-The vector Type",
 },
 {
  msg: "Vector Variables",
  href: "/w08/A#C",
  heading: "A-The vector Type",
 },
 {
  msg: "Vector Initialization",
  href: "/w08/A#D",
  heading: "A-The vector Type",
 },
 {
  msg: "Element Access",
  href: "/w08/A#E",
  heading: "A-The vector Type",
 },
 {
  msg: "Range Checking",
  href: "/w08/A#F",
  heading: "A-The vector Type",
 },
 {
  msg: "Growing & Shrinking",
  href: "/w08/B#A",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Vectors & Loops",
  href: "/w08/B#B",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Common Algorithms",
  href: "/w08/B#C",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Counting Algorithm",
  href: "/w08/B#D",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Cumulative Algorithm",
  href: "/w08/B#E",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Extreme Value",
  href: "/w08/B#F",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Modifying Algorithms",
  href: "/w08/B#G",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Filling & Shuffling",
  href: "/w08/B#H",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Vectors & Functions",
  href: "/w08/B#I",
  heading: "B-Processing Vectors",
 },
 {
  msg: "Memory & Addresses",
  href: "/w08/C#A",
  heading: "C-Memory & Addresses",
 },
 {
  msg: "Naming Concepts",
  href: "/w08/C#B",
  heading: "C-Memory & Addresses",
 },
 {
  msg: "Global Variables",
  href: "/w08/C#C",
  heading: "C-Memory & Addresses",
 },
 {
  msg: "Local Variables",
  href: "/w08/C#D",
  heading: "C-Memory & Addresses",
 },
 {
  msg: "Characteristics of Variables",
  href: "/w08/C#E",
  heading: "C-Memory & Addresses",
 },
 {
  msg: "The sizeof Operator",
  href: "/w08/C#F",
  heading: "C-Memory & Addresses",
 },
 {
  msg: "The Address Operator",
  href: "/w08/C#G",
  heading: "C-Memory & Addresses",
 },
 { msg: "Pointers", href: "/w08/D#A", heading: "D-Pointers" },
 { msg: "Defining Pointers", href: "/w08/D#B", heading: "D-Pointers" },
 {
  msg: "Initializing Pointers",
  href: "/w08/D#C",
  heading: "D-Pointers",
 },
 {
  msg: "Dereferencing Pointers",
  href: "/w08/D#D",
  heading: "D-Pointers",
 },
 { msg: "Pointer Assignment", href: "/w08/D#E", heading: "D-Pointers" },
 { msg: 'The "null" Pointer', href: "/w08/D#F", heading: "D-Pointers" },
 {
  msg: "Digital Images",
  href: "/w08/E#A",
  heading: "E-Pointers & Graphics",
 },
 {
  msg: "RGB Colors",
  href: "/w08/E#B",
  heading: "E-Pointers & Graphics",
 },
 {
  msg: "The RGB Explorer",
  href: "/w08/E#C",
  heading: "E-Pointers & Graphics",
 },
 {
  msg: "Digital Images in C++",
  href: "/w08/E#D",
  heading: "E-Pointers & Graphics",
 },
 {
  msg: "Loading an Image",
  href: "/w08/E#E",
  heading: "E-Pointers & Graphics",
 },
 {
  msg: "More on Loading an Image",
  href: "/w08/E#F",
  heading: "E-Pointers & Graphics",
 },
 {
  msg: "Saving an Image",
  href: "/w08/E#G",
  heading: "E-Pointers & Graphics",
 },
 {
  msg: "Changing the Format",
  href: "/w08/E#H",
  heading: "E-Pointers & Graphics",
 },
 { msg: "Digital Filters", href: "/w09/A#A", heading: "A-Image Filters" },
 {
  msg: "Address Arithmetic",
  href: "/w09/A#B",
  heading: "A-Image Filters",
 },
 { msg: "Iterator Loops", href: "/w09/A#C", heading: "A-Image Filters" },
 {
  msg: "The Darken Filter",
  href: "/w09/A#D",
  heading: "A-Image Filters",
 },
 {
  msg: "Dealing with Channels",
  href: "/w09/A#E",
  heading: "A-Image Filters",
 },
 { msg: "State Filter", href: "/w09/A#F", heading: "A-Image Filters" },
 {
  msg: "Pointers & Structures",
  href: "/w09/A#G",
  heading: "A-Image Filters",
 },
 {
  msg: "Using reinterpret_cast",
  href: "/w09/A#H",
  heading: "A-Image Filters",
 },
 {
  msg: "Introducing Arrays",
  href: "/w09/B#A",
  heading: "B-Introducing Arrays",
 },
 {
  msg: "Array vs. vector",
  href: "/w09/B#B",
  heading: "B-Introducing Arrays",
 },
 {
  msg: "Defining Arrays",
  href: "/w09/B#C",
  heading: "B-Introducing Arrays",
 },
 {
  msg: "Array Initialization",
  href: "/w09/B#D",
  heading: "B-Introducing Arrays",
 },
 {
  msg: "The Allocated Size",
  href: "/w09/B#E",
  heading: "B-Introducing Arrays",
 },
 {
  msg: "Array Selection",
  href: "/w09/B#F",
  heading: "B-Introducing Arrays",
 },
 {
  msg: "Characteristics of Arrays",
  href: "/w09/B#G",
  heading: "B-Introducing Arrays",
 },
 {
  msg: "Pointers & Arrays",
  href: "/w09/C#A",
  heading: "C-Pointers, Arrays & Functions",
 },
 {
  msg: "Pointer Arithmetic & Arrays",
  href: "/w09/C#B",
  heading: "C-Pointers, Arrays & Functions",
 },
 {
  msg: "Dereferencing Arrays",
  href: "/w09/C#C",
  heading: "C-Pointers, Arrays & Functions",
 },
 {
  msg: "Arrays & Functions",
  href: "/w09/C#D",
  heading: "C-Pointers, Arrays & Functions",
 },
 {
  msg: "Decaying Arrays",
  href: "/w09/C#E",
  heading: "C-Pointers, Arrays & Functions",
 },
 {
  msg: "Arrays & Const",
  href: "/w09/C#F",
  heading: "C-Pointers, Arrays & Functions",
 },
 {
  msg: "Arrays and Loops",
  href: "/w09/D#A",
  heading: "D-Arrays & Loops",
 },
 {
  msg: "Counter-Controlled Loops",
  href: "/w09/D#B",
  heading: "D-Arrays & Loops",
 },
 { msg: "Sentinel Loops", href: "/w09/D#C", heading: "D-Arrays & Loops" },
 { msg: "Iterator Loop", href: "/w09/D#D", heading: "D-Arrays & Loops" },
 { msg: "A C++ Idiom", href: "/w09/D#E", heading: "D-Arrays & Loops" },
 {
  msg: "Arrays and Algorithms",
  href: "/w09/E#A",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "Counting Algorithms",
  href: "/w09/E#B",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "Cumulative Algorithms",
  href: "/w09/E#C",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "Extreme Values",
  href: "/w09/E#D",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "Returning a Pointer",
  href: "/w09/E#E",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "Returning an Index",
  href: "/w09/E#F",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "The Fencepost Algorithm",
  href: "/w09/E#G",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "A Reverse Fencepost",
  href: "/w09/E#H",
  heading: "E-Arrays & Algorithms",
 },
 {
  msg: "Searching Algorithms",
  href: "/w10/A#A",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "The Starter Code",
  href: "/w10/A#B",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "The find() Function",
  href: "/w10/A#C",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "Linear Search",
  href: "/w10/A#D",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "Linear Search Efficiency",
  href: "/w10/A#E",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "Improving Linear Search",
  href: "/w10/A#F",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "Binary Search",
  href: "/w10/A#G",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "Implementing Binary Search",
  href: "/w10/A#H",
  heading: "A-Searching Algorithms",
 },
 {
  msg: "An Array Example",
  href: "/w10/B#A",
  heading: "B-Partially-Filled Arrays",
 },
 {
  msg: "Appending Elements",
  href: "/w10/B#B",
  heading: "B-Partially-Filled Arrays",
 },
 {
  msg: "Traversing the Array",
  href: "/w10/B#C",
  heading: "B-Partially-Filled Arrays",
 },
 {
  msg: "Inserting Elements",
  href: "/w10/B#D",
  heading: "B-Partially-Filled Arrays",
 },
 {
  msg: "Applying the Algorithm",
  href: "/w10/B#E",
  heading: "B-Partially-Filled Arrays",
 },
 {
  msg: "Removing Elements",
  href: "/w10/B#F",
  heading: "B-Partially-Filled Arrays",
 },
 {
  msg: "Removing Multiple Elements",
  href: "/w10/B#G",
  heading: "B-Partially-Filled Arrays",
 },
 { msg: "2D Arrays", href: "/w10/C#A", heading: "C-2D Arrays" },
 { msg: "Row Major Order", href: "/w10/C#B", heading: "C-2D Arrays" },
 {
  msg: "2D Array Initialization",
  href: "/w10/C#C",
  heading: "C-2D Arrays",
 },
 {
  msg: "2D Arrays & Functions",
  href: "/w10/C#D",
  heading: "C-2D Arrays",
 },
 {
  msg: "C-Style Strings",
  href: "/w10/D#A",
  heading: "D-C-Style Strings",
 },
 {
  msg: "C-String Basics",
  href: "/w10/D#B",
  heading: "D-C-Style Strings",
 },
 {
  msg: "Array-based C-Strings",
  href: "/w10/D#C",
  heading: "D-C-Style Strings",
 },
 {
  msg: "Pointer-based C-Strings",
  href: "/w10/D#D",
  heading: "D-C-Style Strings",
 },
 {
  msg: "C++ Strings vs. C-Strings",
  href: "/w10/D#E",
  heading: "D-C-Style Strings",
 },
 {
  msg: "C-String Assignment",
  href: "/w10/D#F",
  heading: "D-C-Style Strings",
 },
 {
  msg: "The strncpy Function",
  href: "/w10/D#G",
  heading: "D-C-Style Strings",
 },
 {
  msg: "The strcat Functions",
  href: "/w10/D#H",
  heading: "D-C-Style Strings",
 },
 {
  msg: "Comparing C-Strings",
  href: "/w10/D#I",
  heading: "D-C-Style Strings",
 },
 {
  msg: "The strlen Function",
  href: "/w10/E#A",
  heading: "E-Writing C-String Functions",
 },
 {
  msg: "The strcpy Function",
  href: "/w10/E#B",
  heading: "E-Writing C-String Functions",
 },
 {
  msg: "The strcmp Function",
  href: "/w10/E#C",
  heading: "E-Writing C-String Functions",
 },
 {
  msg: "Writing Your Own Functions",
  href: "/w10/E#D",
  heading: "E-Writing C-String Functions",
 },
 {
  msg: "Find First",
  href: "/w10/E#E",
  heading: "E-Writing C-String Functions",
 },
 {
  msg: "Find Last",
  href: "/w10/E#F",
  heading: "E-Writing C-String Functions",
 },
 {
  msg: "Find First of Any",
  href: "/w10/E#G",
  heading: "E-Writing C-String Functions",
 },
 {
  msg: "Finding Substrings",
  href: "/w10/E#H",
  heading: "E-Writing C-String Functions",
 },
 { msg: "The Shell", href: "/w11/A#A", heading: "A-The Command Line" },
 {
  msg: "The Command Line",
  href: "/w11/A#B",
  heading: "A-The Command Line",
 },
 {
  msg: "Command-Line Arguments",
  href: "/w11/A#C",
  heading: "A-The Command Line",
 },
 {
  msg: "Using Command-Line Arguments",
  href: "/w11/A#D",
  heading: "A-The Command Line",
 },
 {
  msg: "Traversing the Arguments",
  href: "/w11/A#E",
  heading: "A-The Command Line",
 },
 {
  msg: "Converting Arguments",
  href: "/w11/A#F",
  heading: "A-The Command Line",
 },
 {
  msg: "Introducing the Heap",
  href: "/w11/B#A",
  heading: "B-Dynamic Memory",
 },
 { msg: "Stack vs. Heap", href: "/w11/B#B", heading: "B-Dynamic Memory" },
 {
  msg: "The new Operator",
  href: "/w11/B#C",
  heading: "B-Dynamic Memory",
 },
 { msg: "Dyanmic Arrays", href: "/w11/B#D", heading: "B-Dynamic Memory" },
 {
  msg: "Dynamic Objects",
  href: "/w11/B#E",
  heading: "B-Dynamic Memory",
 },
 { msg: "Freeing Memory", href: "/w11/B#F", heading: "B-Dynamic Memory" },
 {
  msg: "Memory Management",
  href: "/w11/C#A",
  heading: "C-Smart Pointers",
 },
 { msg: "Memory Leaks", href: "/w11/C#B", heading: "C-Smart Pointers" },
 {
  msg: "Dangling Pointers",
  href: "/w11/C#C",
  heading: "C-Smart Pointers",
 },
 { msg: "Double Deletes", href: "/w11/C#D", heading: "C-Smart Pointers" },
 { msg: "Smart Pointers", href: "/w11/C#E", heading: "C-Smart Pointers" },
 {
  msg: "Shared Pointers",
  href: "/w11/C#F",
  heading: "C-Smart Pointers",
 },
 {
  msg: "Unique Pointers",
  href: "/w11/C#G",
  heading: "C-Smart Pointers",
 },
 {
  msg: "Smart Pointers & Functions",
  href: "/w11/C#H",
  heading: "C-Smart Pointers",
 },
 {
  msg: "Unique Pointers and Containers",
  href: "/w11/C#I",
  heading: "C-Smart Pointers",
 },
 {
  msg: "Unique Pointers and Dynamic Arrays",
  href: "/w11/C#J",
  heading: "C-Smart Pointers",
 },
 {
  msg: "The Iron Age",
  href: "/w11/D#A",
  heading: "D-The Problem with Structures",
 },
 {
  msg: "User-Defined Types",
  href: "/w11/D#B",
  heading: "D-The Problem with Structures",
 },
 {
  msg: "Object-Based Programming",
  href: "/w11/D#C",
  heading: "D-The Problem with Structures",
 },
 {
  msg: "Time as a Structure",
  href: "/w11/D#D",
  heading: "D-The Problem with Structures",
 },
 {
  msg: "Type Invariants",
  href: "/w11/D#E",
  heading: "D-The Problem with Structures",
 },
 {
  msg: "A Scenario",
  href: "/w11/D#F",
  heading: "D-The Problem with Structures",
 },
 {
  msg: "The Problem",
  href: "/w11/D#G",
  heading: "D-The Problem with Structures",
 },
 {
  msg: "Information Hiding",
  href: "/w11/E#A",
  heading: "E-Member Functions",
 },
 {
  msg: "The Public Interface",
  href: "/w11/E#B",
  heading: "E-Member Functions",
 },
 {
  msg: "Member Functions",
  href: "/w11/E#C",
  heading: "E-Member Functions",
 },
 {
  msg: "Proving the Interface",
  href: "/w11/E#D",
  heading: "E-Member Functions",
 },
 {
  msg: "The Implementation File",
  href: "/w11/E#E",
  heading: "E-Member Functions",
 },
 {
  msg: "Implementing Member Functions",
  href: "/w11/E#F",
  heading: "E-Member Functions",
 },
 {
  msg: "Introducing OOP",
  href: "/w12/A#A",
  heading: "A-Objects & Classes",
 },
 {
  msg: "What are Objects",
  href: "/w12/A#B",
  heading: "A-Objects & Classes",
 },
 {
  msg: "State and Behavior",
  href: "/w12/A#C",
  heading: "A-Objects & Classes",
 },
 {
  msg: "What are Classes",
  href: "/w12/A#D",
  heading: "A-Objects & Classes",
 },
 {
  msg: "What is Encapsulation",
  href: "/w12/A#E",
  heading: "A-Objects & Classes",
 },
 {
  msg: "Real World Encapsulation",
  href: "/w12/A#F",
  heading: "A-Objects & Classes",
 },
 {
  msg: "The Wall of Abstraction",
  href: "/w12/B#A",
  heading: "B-Encapsulation",
 },
 {
  msg: "Class Definition Syntax",
  href: "/w12/B#B",
  heading: "B-Encapsulation",
 },
 {
  msg: "Public and Private",
  href: "/w12/B#C",
  heading: "B-Encapsulation",
 },
 {
  msg: "The Implicit Parameter",
  href: "/w12/B#D",
  heading: "B-Encapsulation",
 },
 {
  msg: "The Pointer this",
  href: "/w12/B#E",
  heading: "B-Encapsulation",
 },
 {
  msg: "The sum Member Function",
  href: "/w12/B#F",
  heading: "B-Encapsulation",
 },
 {
  msg: "Setters",
  href: "/w12/C#A",
  heading: "C-Mutators & Constructors",
 },
 {
  msg: "Getter & Setter Patterns",
  href: "/w12/C#B",
  heading: "C-Mutators & Constructors",
 },
 {
  msg: "Constructors",
  href: "/w12/C#C",
  heading: "C-Mutators & Constructors",
 },
 {
  msg: "Member Initialization",
  href: "/w12/C#D",
  heading: "C-Mutators & Constructors",
 },
 {
  msg: "Working Constructor",
  href: "/w12/C#E",
  heading: "C-Mutators & Constructors",
 },
 {
  msg: "Assignment vs. Initialization",
  href: "/w12/C#F",
  heading: "C-Mutators & Constructors",
 },
 {
  msg: "The Initializer List",
  href: "/w12/C#G",
  heading: "C-Mutators & Constructors",
 },
 {
  msg: "The Working Constructor",
  href: "/w12/D#A",
  heading: "D-More on Classes",
 },
 {
  msg: "Conversion Constructors",
  href: "/w12/D#B",
  heading: "D-More on Classes",
 },
 {
  msg: "Implicit vs. Explicit",
  href: "/w12/D#C",
  heading: "D-More on Classes",
 },
 {
  msg: "Assign, Copy & Destroy",
  href: "/w12/D#D",
  heading: "D-More on Classes",
 },
 {
  msg: "Static Data Members",
  href: "/w12/D#E",
  heading: "D-More on Classes",
 },
 {
  msg: "Static Member Functions",
  href: "/w12/D#F",
  heading: "D-More on Classes",
 },
 {
  msg: "static const Data Members",
  href: "/w12/D#G",
  heading: "D-More on Classes",
 },
 { msg: "Classification", href: "/w12/E#A", heading: "E-Inheritance" },
 { msg: "Inheritance", href: "/w12/E#B", heading: "E-Inheritance" },
 { msg: "Person <- Student", href: "/w12/E#C", heading: "E-Inheritance" },
 { msg: "The UML Diagram", href: "/w12/E#D", heading: "E-Inheritance" },
 { msg: "Inherited Members", href: "/w12/E#E", heading: "E-Inheritance" },
 {
  msg: "Private Base-class Members",
  href: "/w12/E#F",
  heading: "E-Inheritance",
 },
 {
  msg: "Base-class Constructors",
  href: "/w13/A#A",
  heading: "A-Derived Constructors",
 },
 {
  msg: "Derived-class Constructors",
  href: "/w13/A#B",
  heading: "A-Derived Constructors",
 },
 {
  msg: "Constructor Chaining",
  href: "/w13/A#C",
  heading: "A-Derived Constructors",
 },
 {
  msg: "Default Constructors",
  href: "/w13/A#D",
  heading: "A-Derived Constructors",
 },
 {
  msg: "Calling the Base Constructor",
  href: "/w13/A#E",
  heading: "A-Derived Constructors",
 },
 {
  msg: "Protected Members",
  href: "/w13/A#F",
  heading: "A-Derived Constructors",
 },
 {
  msg: "Virtual Member Functions",
  href: "/w13/B#A",
  heading: "B-Overriding Functions",
 },
 {
  msg: "Implementing toString()",
  href: "/w13/B#B",
  heading: "B-Overriding Functions",
 },
 {
  msg: "Overriding toString()",
  href: "/w13/B#C",
  heading: "B-Overriding Functions",
 },
 {
  msg: "Implementing Student::toString()",
  href: "/w13/B#D",
  heading: "B-Overriding Functions",
 },
 {
  msg: "Combining toString()",
  href: "/w13/B#E",
  heading: "B-Overriding Functions",
 },
 {
  msg: "The override Keyword",
  href: "/w13/B#F",
  heading: "B-Overriding Functions",
 },
 {
  msg: "The Stream Class Hierarchy",
  href: "/w13/B#G",
  heading: "B-Overriding Functions",
 },
 {
  msg: "Stream Substitutability",
  href: "/w13/B#H",
  heading: "B-Overriding Functions",
 },
 {
  msg: "Substitution vs. Conversion",
  href: "/w13/B#I",
  heading: "B-Overriding Functions",
 },
 {
  msg: "Class Relationships",
  href: "/w13/C#A",
  heading: "C-Polymorphism",
 },
 {
  msg: "Polymorphic Inheritance",
  href: "/w13/C#B",
  heading: "C-Polymorphism",
 },
 {
  msg: "Static Polymorphism",
  href: "/w13/C#C",
  heading: "C-Polymorphism",
 },
 {
  msg: "A Perplexing Problem",
  href: "/w13/C#D",
  heading: "C-Polymorphism",
 },
 {
  msg: "The Slicing Problem",
  href: "/w13/C#E",
  heading: "C-Polymorphism",
 },
 {
  msg: "References & Pointers",
  href: "/w13/C#F",
  heading: "C-Polymorphism",
 },
 {
  msg: "Polymorphic Functions",
  href: "/w13/C#G",
  heading: "C-Polymorphism",
 },
 {
  msg: "Polymorphic Lists",
  href: "/w13/C#H",
  heading: "C-Polymorphism",
 },
 {
  msg: "Pointers to the Rescue?",
  href: "/w13/C#I",
  heading: "C-Polymorphism",
 },
 {
  msg: "Maybe Smart Pointers",
  href: "/w13/C#J",
  heading: "C-Polymorphism",
 },
 {
  msg: "Early & Late Binding",
  href: "/w13/D#A",
  heading: "D-Class Relationships",
 },
 {
  msg: "How Late Binding Works",
  href: "/w13/D#B",
  heading: "D-Class Relationships",
 },
 {
  msg: "Multiple Inheritance",
  href: "/w13/D#C",
  heading: "D-Class Relationships",
 },
 {
  msg: "Contraction",
  href: "/w13/D#D",
  heading: "D-Class Relationships",
 },
 {
  msg: "Private Inheritance",
  href: "/w13/D#E",
  heading: "D-Class Relationships",
 },
 {
  msg: "Composition",
  href: "/w13/D#F",
  heading: "D-Class Relationships",
 },
 {
  msg: "Specification Inheritance",
  href: "/w13/E#A",
  heading: "E-Specification Inheritance",
 },
 {
  msg: "Abstract Classes",
  href: "/w13/E#B",
  heading: "E-Specification Inheritance",
 },
 {
  msg: "Creating an Abstract Class",
  href: "/w13/E#C",
  heading: "E-Specification Inheritance",
 },
 {
  msg: "Using an Abstract Class",
  href: "/w13/E#D",
  heading: "E-Specification Inheritance",
 },
 {
  msg: "A Triangle Example",
  href: "/w13/E#E",
  heading: "E-Specification Inheritance",
 },
 {
  msg: "Redefining Functions",
  href: "/w13/E#F",
  heading: "E-Specification Inheritance",
 },
 {
  msg: "Final Classes",
  href: "/w13/E#G",
  heading: "E-Specification Inheritance",
 },
];

export default chapters;
